### PR TITLE
translated english to simplified Chinese

### PR DESCRIPTION
**Pull request by ywalia01**

### CODE REVIEW

**Comment by maccyber** [comment]
Woho - awesome,

1. Can you please run `yarn lintfix`

2. And add something like this to nuxt.config.js under modules['i18n'].locales:

```js
...
          {
            name: 'Chinese',
            code: 'zh-Hans',
            iso: 'zh-Hans',
            file: 'zh-Hans.js',
            dir: 'ltr'
          },
...
```

If you now run `yarn` and then `yarn dev` and open the web-browser on http://localhost:3000 you will find your language in the dropdown-list.

See that it works at expected.

**Comment by ywalia01** [comment]
> Woho - awesome,
> 
> 1. Can you please run `yarn lintfix`
> 2. And add something like this to nuxt.config.js under modules['i18n'].locales:
> 
> ```js
> ...
>           {
>             name: 'Chinese',
>             code: 'zh-Hans',
>             iso: 'zh-Hans',
>             file: 'zh-Hans.js',
>             dir: 'ltr'
>           },
> ...
> ```
> 
> If you now run `yarn` and then `yarn dev` and open the web-browser on http://localhost:3000 you will find your language in the dropdown-list.
> 
> See that it works at expected.

Okay, will do that

**Comment by ywalia01** [comment]
Hey, I've done the 2 tasks:
    >yarn lintfix
    >add the lang info to nuxt.config.js
But when I try to run yarn dev it is continuously giving me errors.

**Comment by maccyber** [comment]
Looks good to me :-) (but I don't know the language)
Thanks

Deployed here: https://bigfive-test.com/zh-Hans

**Pull request merged**
